project:
  type: website
  resources:
    - assets
    - seminar/assets

format:
  revealjs:
    width: 1600
    height: 900
    margin: 0.05
    center: false

    theme:
      - default
      - assets/ntnu.scss

    logo: assets/ntnu-logo.svg
    footer: "NTNU • Global Sensitivity Analysis • 3–4 Feb 2026"
    slide-number: true

    progress: true
    controlsLayout: edges
    navigationMode: linear
    html-math-method: mathjax
